<?php

/**
 * @file
 * Primary module hooks for Mix module.
 */

/**
 * Implements hook_form_alter().
 */
function mix_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Hide revision field.
  $currentUser = \Drupal::currentUser();
  $hideRevisionField = \Drupal::config('mix.settings')->get('hide_revision_field');
  if ($currentUser->id() != 1 && $hideRevisionField) {
    $form['revision_information']['#access'] = FALSE;
  }
}

/**
 * Implements hook_page_top().
 */
function mix_page_top(array &$page_top) {
  $environmentIndicator = \Drupal::state()->get('mix.environment_indicator');
  if ($environmentIndicator) {
    $page_top['mix_environment_indicator'] = [
      '#type' => 'inline_template',
      '#template' => '<div id="mix-environment-indicator" style="color: #fff; background: orange; text-align: center;">{{ env }}</div>',
      '#context' => [
        'env' => $environmentIndicator,
      ],
      '#cache' => [
        'tags' => [
          'mix:environment-indicator',
        ],
      ],
    ];
  }
}

/**
 * Remove the "Generator" meta tag from the <head> section.
 */
function mix_page_attachments_alter(array &$attachments): void {
  if (\Drupal::config('mix.settings')->get('remove_x_generator')) {
    foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
      if ($attachment[1] == 'system_meta_generator') {
        unset($attachments['#attached']['html_head'][$key]);
      }
    }
  }
}
