<?php

/**
 * @file
 * Primary module hooks for Mix module.
 */

/**
 * Implements hook_form_alter().
 */
function mix_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  // Hide revision field.
  $currentUser = \Drupal::currentUser();
  $hide_revision_field = \Drupal::config('mix.settings')->get('hide_revision_field');
  if ($currentUser->id() != 1 && $hide_revision_field) {
    $form['revision_information']['#access'] = FALSE;
  }
}

/**
 * Implements hook_page_top().
 */
function mix_page_top(array &$page_top) {
  $env = \Drupal::state()->get('mix.environment_indicator');
  if ($env) {
    $page_top['mix_environment_indicator'] = [
      '#type' => 'inline_template',
      '#template' => '<div style="color: #fff; background: orange; text-align: center;">{{ env }}</div>',
      '#context' => [
        'env' => $env,
      ],
    ];
  }
}
