# Schema for the configuration files of the Mix module.
mix.settings:
  type: config_object
  label: 'Mix settings'
  mapping:
    hide_revision_field:
      type: boolean
      label: 'Hide revision field'
    dev_mode:
      type: boolean
      label: 'Enable development mode'
    remove_x_generator:
      type: boolean
      label: 'Remove X-Generator'
    error_page:
      type: mapping
      label: 'Error page settings'
      mapping:
        mode:
          type: boolean
          label: 'Enable custom error page'
        content:
          type: string
          label: 'Error page content'
    config_import_ignore:
      type: mapping
      label: 'Config import ignore'
      mapping:
        mode:
          type: boolean
          label: 'Enable config import ignore'
        content:
          type: string
          label: 'Ignored config names'
