# Schema for the configuration files of the Mix module.
mix.settings:
  type: config_object
  label: 'Mix settings'
  mapping:
    hide_revision_field:
      type: boolean
      label: 'Hide revision field'
      translatable: true
